Repository Ullaakut/astronomer, pull requests merged in 2019-07, with the labels that each got.

#21 Compute percentiles for overall trust
  compute.go
  console.go
  main.go
  query.go
  query_test.go
Labels: bug

#25 Fix GolangCI issues
  factors.go
  gql.go
  query.go
Labels: enhancement

#38 Change rating system to use letters instead of %
  pkg/signature/send.go
  pkg/trust/factors.go
  pkg/trust/render.go
  pkg/trust/render_test.go
Labels: enhancement

#39 Fix bugs with low amount of stargazers
  pkg/gql/fetch.go
  pkg/trust/compute.go
Labels: bug

#48 Improve the docker command in README
  README.md
Labels: documentation, enhancement

#49 Document homebrew tap
  README.md
Labels: documentation

#50 Update backoff dependency
  go.mod
  go.sum
  pkg/gql/fetch.go
Labels: dependencies

#51 progress bar without hack
  pkg/gql/fetch.go
Labels: bug, enhancement
